import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className="bg-gradient-to-t from-purple-200 via-green-200 to-yellow-200 "></body> */}
      {/* bg-gradient-to-t from-orange-100 to-yellow-10 */}
      <body className="bg-gradient-to-t from-orange-100/10 to-yellow-100/10">
        {children}
      </body>
    </html>
  );
}
